---
language: java
jdk:
- openjdk7
before_install: git clone https://github.com/BuildCraft/BuildCraft-Localization.git
  ../BuildCraft-Localization
install: "./gradlew setupCIWorkspace -S"
script: "./gradlew build -S"
env:
  global: TERM=dumb
